### ISSUE TITLE
Classes not compiled before post-processor plugin 

### ISSUE THREAD

**Issue by slavabedr** [aweigold/idea-plugin-jibx#1]
The JiBX Idea Plugin (https://github.com/aweigold/idea-plugin-jibx) no longer works in 2017.2

The classes are not compiled before the builder is invoked.

```
2017-08-07 11:14:28,864 [ 123390]  ERROR - l.BuildProcessClasspathManager - Cannot add jibx-extras.jar from 'JiBX Idea Plugin 0.2' to external compiler classpath: home directory of plugin not found 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.b(BuildProcessClasspathManager.java:109)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.a(BuildProcessClasspathManager.java:58)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.getBuildProcessPluginsClasspath(BuildProcessClasspathManager.java:44)
	at com.intellij.compiler.server.BuildManager.a(BuildManager.java:1240)
	at com.intellij.compiler.server.BuildManager.a(BuildManager.java:794)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-08-07 11:14:28,899 [ 123425]  ERROR - l.BuildProcessClasspathManager - IntelliJ IDEA 2017.2.1  Build #IU-172.3544.35 
2017-08-07 11:14:28,899 [ 123425]  ERROR - l.BuildProcessClasspathManager - JDK: 1.8.0_112 
2017-08-07 11:14:28,899 [ 123425]  ERROR - l.BuildProcessClasspathManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2017-08-07 11:14:28,899 [ 123425]  ERROR - l.BuildProcessClasspathManager - Vendor: Oracle Corporation 
2017-08-07 11:14:28,899 [ 123425]  ERROR - l.BuildProcessClasspathManager - OS: Windows 7 
2017-08-07 11:14:28,899 [ 123425]  ERROR - l.BuildProcessClasspathManager - Last Action:  
2017-08-07 11:14:28,899 [ 123425]  ERROR - l.BuildProcessClasspathManager - Cannot add stax-api.jar from 'JiBX Idea Plugin 0.2' to external compiler classpath: home directory of plugin not found 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.b(BuildProcessClasspathManager.java:109)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.a(BuildProcessClasspathManager.java:58)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.getBuildProcessPluginsClasspath(BuildProcessClasspathManager.java:44)
	at com.intellij.compiler.server.BuildManager.a(BuildManager.java:1240)
	at com.intellij.compiler.server.BuildManager.a(BuildManager.java:794)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-08-07 11:14:28,900 [ 123426]  ERROR - l.BuildProcessClasspathManager - IntelliJ IDEA 2017.2.1  Build #IU-172.3544.35 
2017-08-07 11:14:28,900 [ 123426]  ERROR - l.BuildProcessClasspathManager - JDK: 1.8.0_112 
2017-08-07 11:14:28,900 [ 123426]  ERROR - l.BuildProcessClasspathManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2017-08-07 11:14:28,900 [ 123426]  ERROR - l.BuildProcessClasspathManager - Vendor: Oracle Corporation 
2017-08-07 11:14:28,900 [ 123426]  ERROR - l.BuildProcessClasspathManager - OS: Windows 7 
2017-08-07 11:14:28,900 [ 123426]  ERROR - l.BuildProcessClasspathManager - Last Action:  
2017-08-07 11:14:28,900 [ 123426]  ERROR - l.BuildProcessClasspathManager - Cannot add wstx-asl.jar from 'JiBX Idea Plugin 0.2' to external compiler classpath: home directory of plugin not found 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.b(BuildProcessClasspathManager.java:109)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.a(BuildProcessClasspathManager.java:58)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.getBuildProcessPluginsClasspath(BuildProcessClasspathManager.java:44)
	at com.intellij.compiler.server.BuildManager.a(BuildManager.java:1240)
	at com.intellij.compiler.server.BuildManager.a(BuildManager.java:794)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-08-07 11:14:28,900 [ 123426]  ERROR - l.BuildProcessClasspathManager - IntelliJ IDEA 2017.2.1  Build #IU-172.3544.35 
2017-08-07 11:14:28,900 [ 123426]  ERROR - l.BuildProcessClasspathManager - JDK: 1.8.0_112 
2017-08-07 11:14:28,900 [ 123426]  ERROR - l.BuildProcessClasspathManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2017-08-07 11:14:28,901 [ 123427]  ERROR - l.BuildProcessClasspathManager - Vendor: Oracle Corporation 
2017-08-07 11:14:28,901 [ 123427]  ERROR - l.BuildProcessClasspathManager - OS: Windows 7 
2017-08-07 11:14:28,901 [ 123427]  ERROR - l.BuildProcessClasspathManager - Last Action:  
2017-08-07 11:14:28,901 [ 123427]  ERROR - l.BuildProcessClasspathManager - Cannot add xpp3.jar from 'JiBX Idea Plugin 0.2' to external compiler classpath: home directory of plugin not found 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.b(BuildProcessClasspathManager.java:109)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.a(BuildProcessClasspathManager.java:58)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.getBuildProcessPluginsClasspath(BuildProcessClasspathManager.java:44)
	at com.intellij.compiler.server.BuildManager.a(BuildManager.java:1240)
	at com.intellij.compiler.server.BuildManager.a(BuildManager.java:794)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by aweigold** [comment]
Thanks for reporting.  I haven't maintained this in a few years, but when I get some time, I'll see if I can make a fix, or feel free to submit a PR.
